# Generated by Django 5.1.2 on 2024-11-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='mensaje',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='autor',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
